webpong/users/urls.py
from django.urls import path
from django.contrib.auth.views import LogoutView, LoginView

from . import views


app_name = 'users'

urlpatterns = [
    path('', views.index, name='index'),
    path(
        'login/',
        LoginView.as_view(template_name='users/login.html'),
        name='login'
    ),
    path(
        'logout/',
        LogoutView.as_view(template_name='users/logged_out.html'),
        name='logout'
    ),
    path('signup/', views.SingUp.as_view(), name='signup'),
]

webpong/webpong/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('', include('users.urls', namespace='users')),
    path('admin/', admin.site.urls),
]

webpong/users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import get_user_model

User = get_user_model()


class CreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = User
        fields = ('first_name', 'last_name', 'username', 'email')

webpong/users/views.py
from django.shortcuts import render
from django.views.generic import CreateView
from django.urls import reverse_lazy

from .forms import CreationForm

def index(request):
    template = 'index.html'
    return render(request, template)

class SingUp(CreateView):
    form_class = CreationForm
    success_url = reverse_lazy('posts:index')
    template_name = 'users/signup.html'

webpong/templates/includes/form_fields.html
{% csrf_token %}
{% for field in form %}
<div
  {% if field.field.required %} 
    aria-required="true"
  {% else %}
    aria-required="false"
  {% endif %}
  >
  <label for="{{ field.id_for_label }}">
    {{ field.label }}
    {% if field.field.required %}
      <span>*</span>
    {% endif %}
  </label>
  <div>
    {{ field }}
    {% if field.help_text %}
      <small id="{{ field.id_for_label }}-help">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
</div>
{% endfor %}

webpong/templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>Basic Pong HTML Game</title>
  <meta charset="UTF-8">
  <link rel="stylesheet" href={% static 'css/index.css' %}>
</head>
<body>
  {% if user.is_authenticated %}
    <a href="{% url 'users:logout' %}">Выйти</a>
  {% else %}
    <form method="post" action="{% url 'users:signup' %}">
      {% include 'includes/form_fields.html' %}
      <div>
        <button type="submit" class="btn btn-primary">
          Зарегистрироваться
        </button>
      </div>
    </form>
  {% endif %}
  <canvas width="800" height="800" id="game"></canvas>
  <script type="text/javascript" src={% static 'script/game.js' %}></script>
  {% if user.is_authenticated %}
    *Table*
  {% else %}
    <form method="post" action="{% url 'users:login' %}">
      {% include 'includes/form_fields.html' %}
      <div>
        <button type="submit" class="btn btn-primary">
          Войти
        </button>
      </div>
    </form>
  {% endif %}
</body>
</html>